### ISSUE TITLE
Dirt 2.0 lagspikes after 1.10.1

### ISSUE THREAD

**Issue by markusa380** [simonowen/dirtfix#5]
I have started experiencing lag problems after the **1.10.1** as they have been before **1.10**.

This is not an issue of dirtfix but maybe this is the right place to seek help.

See this [SteamVR profiler screenshot](https://imgur.com/OZ9BPEx)

**Comment by simonowen** [comment]
The CPU frame processing takes the same amount of time as normal, but it's starting late in the cases you've highlighted.  The GPU is close to capacity too, so any slight delay will mean it's unable to maintain the full 90fps.

I'd suggest closing as many background processes as you can so the game is the only thing running, to see if that makes a difference.  Reducing the graphics options slightly might prevent small delays from interfering with the framerate.  Most of the time it looks good, so perhaps you're just too close to the edge? :)

**Comment by markusa380** [comment]
I can't reduce the settings any further as they are already on the lowest preset. My rig is above all recommended specs with an i7 and a 1080ti. Before 1.10.1 I could run the game in VR on medium without any issues.

**Comment by simonowen** [comment]
I suspect only Codemastes will be able to help, with additional game optimisations.  It's prettier than DR1, but definitely more demanding on both CPU and GPU.  Maybe they've made some "improvements" that have lead to a performance regression. It'd be worth letting them know on the forum so they can look into the changes.

I'm in a similar position to you with an i7 2600K (oc to 4.3GHz) and GTX 1080ti, and have resigned myself to running at a consistent 45fps instead of 90fps.  Fortunately, driving sims are a bit less sensitive to the lower framerate than some other VR applications.

Still, I'm expecting future system upgrades to make it more likely I can maintain full framerate.
