### ISSUE TITLE
request fix for EA WRC

### ISSUE THREAD

**Issue by ch3coohlink** [simonowen/dirtfix#7]
Since EA WRC is also made by Codemaster (different engine though), maybe it's the same problem and can be fixed by this software too?

**Comment by simonowen** [comment]
I don't own EA WRC but I've read a lot about stuttering caused by shader compilation that happens during gameplay, which is caused by the switch to Unreal Engine. That's nothing dirtfix can help with I'm afraid.

It's very unlikely WRC is affected by the same input issue as CodeMasters fixed it in later versions of DR2. I'd expect the input code of later games to remain fixed. Still, you can try it yourself if you really want to:

- Browse to `C:\Program Files (x86)\DirtFix` and copy the `dinput8_64.dll` file to the clipboard.
- Browse to the EA WRC directory containing the main game .exe file.
- Paste the `dinput8_64.dll` file from above, and rename it to just `dinput8.dll`.
- Launch the game and see if anything has improved.
- To uninstall just delete the `dinput8.dll` file you added above.

My utility just automates the install/uninstall steps above for games known to be affected.
